version: '3'
services:
  bot:
    build: ./bot
    depends_on:
      - geo
    volumes:
      - ./bot:/bot
    command: ruby telegram_bot.rb
  geo:
    build: ./geo
    depends_on:
      - redis
    command: ./geo
  rowery:
    build: ./rowery
    environment:
      - PYTHONUNBUFFERED=0   
    depends_on:
      - redis
    volumes:
      - ./rowery:/rowery
    command: python rowery.py
  redis:
    image: redis:3.2.11-alpine
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
