version: '3'
services:
  bot:
    build: ./bot
    depends_on:
      - geo
    volumes:
      - ./bot:/bot
    command: ruby telegram_bot.rb
  geo:
    build: ./geo
    depends_on:
      - redis
    command: ./geo
  redis:
    image: redis:3.2.11-alpine
    ports:
      - 6379:6379